<a href="https://colab.research.google.com/github/Birusky/Punya-Mariam/blob/main/DAA_P3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np

In [49]:
aList = ["John", 33, "Toronto", True]
print (aList)

['John', 33, 'Toronto', True]


In [50]:
dataMahasiswa = ["Siti Mariam", 2021071004, "Informatika", "DAA", "14/19/2022", "Universitas Pembangunan Jaya"]
print (dataMahasiswa)

['Siti Mariam', 2021071004, 'Informatika', 'DAA', '14/19/2022', 'Universitas Pembangunan Jaya']


In [51]:
bin_colors = ["Red","Green","Blue", "Yellow"]
bin_colors[2]

'Blue'

In [52]:
dataMahasiswa[1]

2021071004

In [53]:
dataMahasiswa[5]

'Universitas Pembangunan Jaya'

In [54]:
bin_colors = ["Red","Green","Blue", "Yellow"]
bin_colors[0:3]

['Red', 'Green', 'Blue']

In [55]:
dataMahasiswa[1:3]

[2021071004, 'Informatika']

In [56]:
bin_colors = ["Red","Green","Blue", "Yellow"]
for aColor in bin_colors:
  print (aColor + "Square")

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [57]:
dataMahasiswa = ["Siti Mariam", 2021071004, "Informatika", "DAA", "14/19/2022", "Universitas Pembangunan Jaya"]
for Kampus in dataMahasiswa:
  print ("UPJ " , Kampus)

UPJ  Siti Mariam
UPJ  2021071004
UPJ  Informatika
UPJ  DAA
UPJ  14/19/2022
UPJ  Universitas Pembangunan Jaya


In [77]:
bin_colors = ("Red","Green","Blue", "Yellow")
bin_colors[2:]

('Blue', 'Yellow')

In [78]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya')

In [81]:
nested_tuple = (100, [200, 400, 600], 300, [400, 800])
nested_tuple[3]

[400, 800]

In [61]:
bin_colors = {"manual_color": "Yellow", "approved_color": "Green", "Refused_color": "Red"}
print (bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'Refused_color': 'Red'}


In [62]:
bin_colors.get("manual_color")

'Yellow'

In [63]:
bin_colors["manual_color"] = "Blue"
print (bin_colors)

{'manual_color': 'Blue', 'approved_color': 'Green', 'Refused_color': 'Red'}


In [64]:
dataMahasiswa = {"Nama": "Siti Mariam", "NIM": "2021071004", "Prodi": "Informatika", "Universitas": "UPJ"}
print (dataMahasiswa)

{'Nama': 'Siti Mariam', 'NIM': '2021071004', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [66]:
green = {'Grass','Leaves'}
print(green)

{'Leaves', 'Grass'}


In [67]:
green = {'Grass','Leaves', 'Leaves'}
print(green) 

{'Leaves', 'Grass'}


In [119]:
yellow = {'dandelions','leaves', 'fire hydrant'}
red = {'fire hydrant','blood','leaves', 'rose'}
print(yellow|red)
print(yellow&red)

{'rose', 'blood', 'dandelions', 'leaves', 'fire hydrant'}
{'leaves', 'fire hydrant'}


In [83]:
import pandas as pd

In [84]:
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])

In [90]:
df.columns = ['id', 'Name', 'Age', 'decision']
df

id    Name  Age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [91]:
df[['Name', 'Age']]

Name  Age
0   Fares   32
1   Elena   23
2  Steven   40

In [93]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [94]:
df.iloc[1:3,:]

id    Name  Age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [96]:
df[df.Age>30]

id    Name  Age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [98]:
df[(df.Age<35)&(df.decision==True)]

id   Name  Age  decision
0  1  Fares   32      True

In [99]:
mhs = pd.DataFrame([
    ['1', 'Informatika', 50, 30, 20],
    ['2', 'Sistem Infomasi', 55, 30, 25],
    ['3', 'Teknik Sipil', 40, 30, 10]])

In [101]:
mhs.columns =['No', 'Prodi', 'Mahasiswa', 'Laki-Laki', 'Perempuan']
mhs

No            Prodi  Mahasiswa  Laki-Laki  Perempuan
0  1      Informatika         50         30         20
1  2  Sistem Infomasi         55         30         25
2  3     Teknik Sipil         40         30         10

In [102]:
myMatrix = np.array([[11,12,13], [21,22,23], [30,31,32]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [30 31 32]]


In [103]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [110]:
myMatrix2 = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [800, 900, 1000]
])

In [111]:
print(f'Sebelum Transpose :\n{myMatrix2}')
myMatrix2_transpose = myMatrix2.transpose()
print(f'Setelah diTranspose :\n{myMatrix2_transpose}')

Sebelum Transpose :
[[ 100  200  300]
 [ 700  600  500]
 [ 800  900 1000]]
Setelah diTranspose :
[[ 100  700  800]
 [ 200  600  900]
 [ 300  500 1000]]


In [112]:
myVector = [25, 26, 27, 28]
print(myVector)

[25, 26, 27, 28]


In [113]:
print(type(myVector))

<class 'list'>


In [115]:
myVector = np.array([25, 26, 27, 28])
print(myVector)

[25 26 27 28]


In [118]:
print(type(myVector))

<class 'numpy.ndarray'>


In [120]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [121]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [122]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [123]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [124]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
